default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: development

test:
  <<: *default
  database: test

production:
  adapter: postgresql
  encoding: unicode
  pool: 5
