# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 92dee544e21c5f83b54e6b96752b4d1f302857f62531846ad6984f66283502731370556b57e23b8b816b35415c3c1b864fb04e1d4d9b71cfe0673281cc441a0a
  sorcery_github_callback_url: http://127.0.0.1:3000/oauth/callback?provider=github
  sorcery_github_key: <%= ENV['SORCERY_GITHUB_KEY'] %>
  sorcery_github_secret: <%= ENV['SORCERY_GITHUB_SECRET'] %>

test:
  secret_key_base: f346fbef65b2b0c61f23087b265da173eaed4fa68491a72fa6b43d3acb0a2b9c3e62f364de2ee42af166d2a5a29532cff1fe870cb1527ed92e7e5dd3662ecdea
  sorcery_github_callback_url: http://127.0.0.1:3000/oauth/callback?provider=github
  sorcery_github_key: <%= ENV['SORCERY_GITHUB_KEY'] %>
  sorcery_github_secret: <%= ENV['SORCERY_GITHUB_SECRET'] %>

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV['SECRET_KEY_BASE'] %>
  sorcery_github_callback_url: <%= ENV['SORCERY_GITHUB_CALLBACK_URL'] %>
  sorcery_github_key: <%= ENV['SORCERY_GITHUB_KEY'] %>
  sorcery_github_secret: <%= ENV['SORCERY_GITHUB_SECRET'] %>
